steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/sftp-pipeline/app:$SHORT_SHA',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/sftp-pipeline/app:$SHORT_SHA'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'run', 'jobs', 'deploy', 'sftp-to-bq-job',
        '--image',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/sftp-pipeline/app:$SHORT_SHA',
        '--region', 'europe-west1',
        '--set-env-vars',
        'SFTP_HOST=sftpgo.feedonomics.com,SFTP_USER=fsd,BQ_PROJECT=$PROJECT_ID,BQ_DATASET=shopping_feeds_new,BQ_TABLE=stock_feed_v2',
        '--set-secrets',
        'SFTP_PASS=sftp-password:latest'
      ]

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/sftp-pipeline/app:$SHORT_SHA'
